version: 2
jobs:
  prepare:
    machine:
      image: ubuntu-1604:201903-01
    
    working_directory: ~/

    steps:
      - run:
          name: Prepare
          command: |
            sudo rm -rf /var/lib/apt/lists/lock
            sudo apt-get update
            sudo rm -rf /var/lib/apt/lists/lock
            sudo apt-get install -yq swig python3-dev build-essential git unzip ncurses-dev libz-dev libssl-dev python subversion gettext gawk wget curl rsync perl libelf-dev python3.5 libpython3.5-stdlib liblzma-dev
            pyenv global 3.5.2

  build_rock_pi_e:
    machine:
      image: ubuntu-1604:201903-01

    environment:
      - REPO_URL: https://github.com/jayanta525/rock-pi-e.git
      - BRANCH: mptcp
      - CONFIG: https://raw.githubusercontent.com/jayanta525/openwrt-circleci/mptcp/config.seed
      - FEEDS: https://raw.githubusercontent.com/jayanta525/openwrt-circleci/mptcp/feeds.conf
      - CACHE: radxa1306-main2-mptcp

    working_directory: ~/
    steps:
      - run:
          name: generate_cache_hash
          command: |
            echo "$CACHE" > /tmp/armv8-cache
      
      - restore_cache:
          keys:
            - cache-{{ checksum "/tmp/armv8-cache" }}

      - run:
          name: Clone and Pull Repo
          no_output_timeout: 60m
          command: |
            git clone --depth 1 -b $BRANCH $REPO_URL openwrt || true
            git config --global user.email "ubuntu@circleci.com"
            git config --global user.name "CircleCI"
            cd openwrt/
            git pull || true
            sudo apt-get update
            sudo apt-get install -yq swig python3-dev zip libelf-dev

      - run:
          name: Update Feeds
          no_output_timeout: 60m
          command: |
            cd openwrt/
            pyenv global 3.5.2
            rm .config || true
            rm feeds.conf || true
            wget $FEEDS -O feeds.conf
            ./scripts/feeds update -a
      - run:
          name: Execute Script
          no_output_timeout: 60m
          command: |
            cd openwrt/
            wget -O - https://raw.githubusercontent.com/jayanta525/openwrt-circleci/mptcp/scripts/clean-feeds.sh | bash
            wget -O - https://raw.githubusercontent.com/jayanta525/openwrt-circleci/mptcp/scripts/feeds-change.sh | bash

      - run:
          name: Install Feeds
          no_output_timeout: 60m
          command: |
            cd openwrt/
            pyenv global 3.5.2
            ./scripts/feeds install -a -d m -p packages
            ./scripts/feeds install -a -d m -p luci
            ./scripts/feeds install -a -d y -f -p mptcp
            wget $CONFIG -O .config
            make defconfig

      - run:
          name: Build toolchain
          no_output_timeout: 60m
          command: |
            cd openwrt/
            pyenv global 3.5.2
            make -j3 download
            make -j3 tools/compile
            make -j3 toolchain/compile
            make -j3 tools/install
            make -j3 toolchain/install

      - run:
          name: Build Kernel
          no_output_timeout: 60m
          command: |
            cd openwrt/
            pyenv global 3.5.2
            make -j3 target/compile

      - run:
          name: Build OpenWrt Image
          no_output_timeout: 60m
          command: |
            cd openwrt/
            pyenv global 3.5.2
            make -j3

      - save_cache:
          key: cache-{{ checksum "/tmp/armv8-cache" }}
          paths:
            - openwrt/

      - run:
          name: Organize image files
          no_output_timeout: 60m
          command: |
            cd openwrt/bin/
            rm -rf packages/
            cd targets/rockchip/armv8/
            zip -r target-package.zip packages/
            rm -rf packages/

      - store_artifacts:
          path: openwrt/bin/

workflows:
  version: 2
  main:
    jobs:
      - prepare:
          filters:
            tags:
              only: /.*/
            branches:
              only: 
                - master
      - build_rock_pi_e:
          requires:
            - prepare
          filters:
            tags:
              only: /.*/
            branches:
              only: 
                - master
