version: 2.1
jobs:
  prepare:
    machine:
      image: 'ubuntu-1604:202004-01'

    environment:
      - TZ: Asia/Kolkata

    steps:
      - run:
          name: Prepare system
          command: |
            sudo timedatectl set-timezone "$TZ"
            sudo rm -rf /var/lib/apt/lists/lock
            sudo apt-get update
            sudo rm -rf /var/lib/apt/lists/lock
            sudo apt-get install -yq subversion build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc zip rsync swig unzip python3-dev

  build:
    machine:
      image: 'ubuntu-1604:202004-01'
    
    environment:
      - REPO_URL: https://github.com/openwrt/openwrt.git
      - REPO_BRANCH: master
      - BUILD_CONFIG: .config-orangepir1
      - TZ: Asia/Kolkata

    steps:      
      - checkout
      
      - restore_cache:
          keys:
            - cache-{{ checksum ".circleci/cache-armv7" }}
      
      - run:
          name: Clone repo
          command: |
            git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt || true
      
      - run:
          name: Update repo
          command: |
            cd openwrt/
            git pull

      - run:
          name: Load .config
          command: |
            cp config/$BUILD_CONFIG openwrt/.config

      - run:
          name: Download Files
          command: |
            cd openwrt/
            make defconfig
            make -j8 download

      - run:
          name: Compile toolchains
          no_output_timeout: 50m
          command: |
            cd openwrt/
            make -j3 tools/compile
            make -j3 toolchain/compile
            make -j3 tools/install
            make -j3 toolchain/install

      - save_cache:
          key: cache-{{ checksum ".circleci/cache-armv7" }}
          paths:
            - openwrt/

workflows:
  version: 2
  main:
    jobs:
      - prepare
      - build:
          requires:
            - prepare