version: 2
jobs:
  build_openwrt:
    machine:
      image: ubuntu-1604:201903-01

    environment:
      - REPO_URL: https://github.com/jayanta525/openwrt.git
      - BRANCH: master
      - CONFIG: config.seed
      - FEEDS: feeds.conf
      - SCRIPT1: scripts/feeds-change.sh
      - SCRIPT2: scripts/opkg-source.sh
      - CACHE: 22sept

    working_directory: ~/
    steps:
      - run:
          name: Prepare for checkout
          command: |
            mkdir github
      - checkout:
          path: github/

      - run:
          name: generate_cache_hash
          command: |
            echo "$CACHE" > /tmp/armv7-cache
      
      - restore_cache:
          keys:
            - cache1-{{ checksum "/tmp/armv7-cache" }}

      - run:
          name: Clone and Pull Repo
          no_output_timeout: 60m
          command: |
            git clone --depth 1 -b $BRANCH $REPO_URL openwrt || true
            git config --global user.email "ubuntu@circleci.com"
            git config --global user.name "CircleCI"
            sudo apt-get update
            sudo apt-get install -yq swig python3-dev zip libelf-dev

      - run:
          name: Clear previous builds
          command: |
            rm -rf openwrt/bin/ || true

      - run:
          name: Update Feeds
          no_output_timeout: 60m
          command: |
            cd openwrt/
            pyenv global 3.5.2
            rm .config || true
            ./scripts/feeds clean
            rm feeds.conf || true
            cp ../github/$FEEDS feeds.conf
            ./scripts/feeds update -a

      - run:
          name: Execute Script-1
          no_output_timeout: 60m
          command: |
            cd openwrt/
            cp ../github/$SCRIPT1 script1.sh
            ./script1.sh

      - run:
          name: Execute Script-2
          no_output_timeout: 60m
          command: |
            cd openwrt/
            cp ../github/$SCRIPT2 script2.sh
            ./script2.sh

      - run:
          name: Install Feeds
          no_output_timeout: 60m
          command: |
            cd openwrt/
            pyenv global 3.5.2
            ./scripts/feeds install -a
            cp ../github/$CONFIG .config
            make defconfig

      - run:
          name: Load custom files
          no_output_timeout: 60m
          command: |
            cp -r github/files/ openwrt/

      - run:
          name: Build toolchain
          no_output_timeout: 60m
          command: |
            cd openwrt/
            pyenv global 3.5.2
            make -j3 download
            make -j3 tools/compile
            make -j3 toolchain/compile
            make -j3 tools/install
            make -j3 toolchain/install

      - run:
          name: Build Kernel
          no_output_timeout: 60m
          command: |
            cd openwrt/
            pyenv global 3.5.2
            make -j3 target/compile

      - run:
          name: Build OpenWrt Image
          no_output_timeout: 60m
          command: |
            cd openwrt/
            pyenv global 3.5.2
            make -j3

      - save_cache:
          key: cache1-{{ checksum "/tmp/armv7-cache" }}
          paths:
            - openwrt/

      - run:
          name: Organize image files
          no_output_timeout: 60m
          command: |
            cd github/ && export COMMITMSG=$(git log -1 HEAD --pretty=format:%s)
            cd ..
            cd openwrt/bin/targets/*/
            zip -r cortexa7-$COMMITMSG.zip cortexa7/
            rm -rf */packages/

      - store_artifacts:
          path: openwrt/bin/targets/

workflows:
  version: 2
  main:
    jobs:
      - build_openwrt:
          filters:
            branches:
              only: 
                - nanopir1-deploy
